name: controlcar_app_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_version: 21
  adaptive_icon_background: "#3DC8EB"
  adaptive_icon_foreground: "assets/icons/icon_rounded.png"
